#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
# List of local libraries


# Path to the current BSP
SEARCH_TARGET_APP_CY8CKIT-062S2-43012=bsps/TARGET_APP_CY8CKIT-062S2-43012

# The search paths for the included middleware
SEARCH_capsense=../mtb_shared/capsense/release-v3.0.0
SEARCH_CY8CKIT-028-SENSE=../mtb_shared/CY8CKIT-028-SENSE/release-v1.0.0
SEARCH_freertos=../mtb_shared/freertos/release-v10.4.305
SEARCH_middleware-ntshell=../mtb_shared/middleware-ntshell/latest-v2.X
SEARCH_retarget-io=../mtb_shared/retarget-io/release-v1.4.0
SEARCH_abstraction-rtos=../mtb_shared/abstraction-rtos/release-v1.7.1
SEARCH_audio-codec-wm8960=../mtb_shared/audio-codec-wm8960/release-v1.0.0
SEARCH_BMI160_driver=../mtb_shared/BMI160_driver/bmi160_v3.9.1
SEARCH_BMM150-Sensor-API=../mtb_shared/BMM150-Sensor-API/bmm150_v2.0.0
SEARCH_cat1cm0p=../mtb_shared/cat1cm0p/release-v1.0.0
SEARCH_clib-support=../mtb_shared/clib-support/release-v1.3.0
SEARCH_cmsis=../mtb_shared/cmsis/release-v5.8.0
SEARCH_core-lib=../mtb_shared/core-lib/release-v1.3.1
SEARCH_core-make=../mtb_shared/core-make/release-v3.0.3
SEARCH_display-oled-ssd1306=../mtb_shared/display-oled-ssd1306/release-v1.0.2
SEARCH_mtb-hal-cat1=../mtb_shared/mtb-hal-cat1/release-v2.2.0
SEARCH_mtb-pdl-cat1=../mtb_shared/mtb-pdl-cat1/release-v3.2.0
SEARCH_recipe-make-cat1a=../mtb_shared/recipe-make-cat1a/release-v2.0.0
SEARCH_sensor-orientation-bmx160=../mtb_shared/sensor-orientation-bmx160/release-v1.0.1
SEARCH_sensor-xensiv-dps3xx=../mtb_shared/sensor-xensiv-dps3xx/release-v1.0.0

# Search libraries added to build
SEARCH_MTB_MK+=$(SEARCH_capsense)
SEARCH_MTB_MK+=$(SEARCH_CY8CKIT-028-SENSE)
SEARCH_MTB_MK+=$(SEARCH_freertos)
SEARCH_MTB_MK+=$(SEARCH_middleware-ntshell)
SEARCH_MTB_MK+=$(SEARCH_retarget-io)
SEARCH_MTB_MK+=$(SEARCH_abstraction-rtos)
SEARCH_MTB_MK+=$(SEARCH_audio-codec-wm8960)
SEARCH_MTB_MK+=$(SEARCH_BMI160_driver)
SEARCH_MTB_MK+=$(SEARCH_BMM150-Sensor-API)
SEARCH_MTB_MK+=$(SEARCH_cat1cm0p)
SEARCH_MTB_MK+=$(SEARCH_clib-support)
SEARCH_MTB_MK+=$(SEARCH_cmsis)
SEARCH_MTB_MK+=$(SEARCH_core-lib)
SEARCH_MTB_MK+=$(SEARCH_core-make)
SEARCH_MTB_MK+=$(SEARCH_display-oled-ssd1306)
SEARCH_MTB_MK+=$(SEARCH_mtb-hal-cat1)
SEARCH_MTB_MK+=$(SEARCH_mtb-pdl-cat1)
SEARCH_MTB_MK+=$(SEARCH_recipe-make-cat1a)
SEARCH_MTB_MK+=$(SEARCH_sensor-orientation-bmx160)
SEARCH_MTB_MK+=$(SEARCH_sensor-xensiv-dps3xx)

-include $(CY_INTERNAL_APP_PATH)/importedbsp.mk
COMPONENTS += MW_CAPSENSE
COMPONENTS += MW_CY8CKIT_028_SENSE
COMPONENTS += MW_FREERTOS
COMPONENTS += MW_MIDDLEWARE_NTSHELL
COMPONENTS += MW_RETARGET_IO
COMPONENTS += MW_ABSTRACTION_RTOS
COMPONENTS += MW_AUDIO_CODEC_WM8960
COMPONENTS += MW_BMI160_DRIVER
COMPONENTS += MW_BMM150_SENSOR_API
COMPONENTS += MW_CAT1CM0P
COMPONENTS += MW_CLIB_SUPPORT
COMPONENTS += MW_CMSIS
COMPONENTS += MW_CORE_LIB
COMPONENTS += MW_CORE_MAKE
COMPONENTS += MW_DISPLAY_OLED_SSD1306
COMPONENTS += MW_MTB_HAL_CAT1
COMPONENTS += MW_MTB_PDL_CAT1
COMPONENTS += MW_RECIPE_MAKE_CAT1A
COMPONENTS += MW_SENSOR_ORIENTATION_BMX160
COMPONENTS += MW_SENSOR_XENSIV_DPS3XX

# Register map file
DEVICE_CY8C624ABZI-S2D44_SVD=$(SEARCH_mtb-pdl-cat1)/devices/COMPONENT_CAT1A/svd/psoc6_02.svd


#
# generate make targets for the graphical editors that are specific to this project
#

bsp-assistant:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bsp-assistant
.PHONY: bsp-assistant

config_bt:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bt-configurator
.PHONY: config_bt

bt-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bt-configurator
.PHONY: bt-configurator

capsense-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name capsense-configurator
.PHONY: capsense-configurator

capsense-tuner:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name capsense-tuner
.PHONY: capsense-tuner

config:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name device-configurator
.PHONY: config

device-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name device-configurator
.PHONY: device-configurator

modlibs:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name library-manager
.PHONY: modlibs

library-manager:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name library-manager
.PHONY: library-manager

config_lin:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name lin-configurator
.PHONY: config_lin

lin-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name lin-configurator
.PHONY: lin-configurator

qspi-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name qspi-configurator
.PHONY: qspi-configurator

seglcd-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name seglcd-configurator
.PHONY: seglcd-configurator

smartio-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name smartio-configurator
.PHONY: smartio-configurator

config_usbdev:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name usbdev-configurator
.PHONY: config_usbdev

usbdev-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name usbdev-configurator
.PHONY: usbdev-configurator

